name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: windows-latest
            name: windows_x86_64
            target: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - name: Install rust version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{matrix.toolchain}}
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --release
    - name: Build Release
      run: cargo build --verbose --release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest-${{matrix.name}}"
        prerelease: false
        title: "Latest Build ${{matrix.name}}"
        files: |
          target/release/vsix-extractor.exe